[package]
name = "sp-timestamp"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate core types and inherents for timestamps."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.48", optional = true }
sp-inherents = { path = "../inherents", default-features = false}
sp-runtime = { path = "../runtime", default-features = false}
sp-std = { path = "../std", default-features = false}

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"thiserror",
]
